# DatasourceProperties
spring:
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/community?characterEnconding=utf-8&useSSL=false&serverTimezone=Hongkong
    username: root
    password: password
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 15
      minimum-idle: 5
      idle-timeout: 30000
    # MailProperties
  mail:
    username: 1905921852@qq.com
    password: fzmvcuhogmejejjg
    host: smtp.qq.com
    protocol: smtps
    #开启加密验证
    properties:
      mail:
        smtp:
          ssl:
            enable: true
  #redisProperties
  redis:
    database: 11
    host: localhost
    port: 6379
  #kafkaProperties
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: community-consumer-group
      enable-auto-commit: true
      auto-commit-interval: 3000
  #elasticsearchProperties
  elasticsearch:
    uris: 127.0.0.1:9200
  #taskExecutionProperties
  task:
    execution:
      pool:
        core-size: 5
        max-size: 15
        queue-capacity: 100
    #taskSchedulingProperties
    scheduling:
      pool:
        size: 5
  #quartzProperties
  quartz:
    job-store-type: jdbc
    scheduler-name: communityScheduler
    properties:
      org:
        quartz:
          scheduler:
            # 若是集群下，每个instanceId必须唯一
            instanceId: AUTO
          threadPool:
            #一般使用这个便可
            class: org.quartz.simpl.SimpleThreadPool
            #线程数量，不会动态增加
            threadCount: 5
          jobStore:
            #选择JDBC的存储方式
            class: org.springframework.scheduling.quartz.LocalDataSourceJobStore
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            isClustered: true
# MybatisProperties
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: sxx.xwl.community.community.entity
  configuration:
    use-generated-keys: true
    map-underscore-to-camel-case: true


